listen:
  - 0.0.0.0:10101
endpoint:
  'task':
    type: task_runner
  'curl/sleep':
    type: http_request
    method: GET
    parameters:
      url: http://csiuo.com/sleep.php
schedule:
  testschedule:
    url: "file://example_schedule.json"
trust:
  cert_dir: "certs"
