listen:
  - 0.0.0.0:10101
endpoint:
  'task':
    type: task_runner
    concurrency: -1
    queue: false
    authenticaton: signature
  'curl/sleep':
    type: http_request
    method: GET
    concurrency: -1
    queue: false
    parameters:
      url: http://csiuo.com/sleep.php
  'runit/whoami':
    type: bash
    concurrency: 2
    parameters:
      cmd: "sleep 10"
schedule:
  testschedule:
    url: "file://example_schedule.json"
trust:
  cert_dir: "certs"
